### ISSUE TITLE
no local downloaded data automatically

### ISSUE THREAD

**Issue by Lacro59** [Lacro59/playnite-metadatalocal-plugin#11]
from KindleShrimpDelegate on forum (https://playnite.link/forum/thread-291-post-3269.html#pid3269)

```
DenalB Wrote:
I just downloaded and installed version 0.4 of the plugin. Now I changed the setting for description in metadata options to use "Metadata Local" at first. Then I tried downloading meta data for some steam games but the description didn't change into German language.

But when editing the metadata manually and switch to "Metadata Local" as source it works and the description is in German now.

What could be the problem that this doesn't work for automatic download of the metadata?  Huh
```

the exact same is happening with the latest version, please fix it. Thanks!

**Comment by RaikoKitame** [comment]
The problem is here in the 1.2 version too... Could you fix it please?

**Comment by Lacro59** [comment]
Can you try with the v2.0 for Playnite9?
If possible.

**Comment by forenta** [comment]
Same issue here in Playnite 9. If I manually grab the Metadata with the Plug-In, I'm asked to select platform & game - but nothing happens automatically as I set MetadataLocal as the main and only source for descriptions in case of new games.

**Comment by Lacro59** [comment]
The store selection is only with manual action.
When you update your libraries, the plugin get only the localised description on the store of game; if the plugin is the first metadata for the description field.

**Comment by forenta** [comment]
> The store selection is only with manual action. When you update your libraries, the plugin get only the localised description on the store of game; if the plugin is the first metadata for the description field.
Maybe the manually enabled store selection could be the reason why it doesn't grab anything at all in our case!?

**Comment by Lacro59** [comment]
Do you want to have the selection of stores when you update your library?

**Comment by Lacro59** [comment]
Any news?
